language: node_js
node_js:
  - "8"
  - "9"
cache: yarn

install: yarn
script:
  - yarn lint

jobs:
  include:
    - stage: yarn build
      if: tag IS present
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "$EMAIL_ADDRESS"
        api_key: "$AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
